AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TinuMind Tasks API

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Environment:
      Variables:
        MONGODB_URI: !Ref MongoUri
        DB_NAME: TinumindDB
        COLLECTION_NAME: Tasks

Parameters:
  MongoUri:
    Type: String
    Description: MongoDB connection URI

Resources:
  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ./task.js
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
