AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TinuMind Tasks API

Parameters:
  MongoDbUri:
    Type: String
    Description: MongoDB connection URI

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Environment:
      Variables:
        MONGODB_URI: !Ref MongoDbUri
        DB_NAME: TinumindDB
        COLLECTION_NAME: Tasks



Resources:
  PostTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: postTasks.handler
      Runtime: nodejs20.x
      CodeUri: ./
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: POST

  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getTasks.handler
      Runtime: nodejs20.x
      CodeUri: ./
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: GET

  DeleteTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deleteTasks.handler
      Runtime: nodejs20.x
      CodeUri: ./
      Events:
        DeleteApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: DELETE

  UpdateTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: UpdateTasks.handler
      Runtime: nodejs20.x
      CodeUri: ./
      Events:
        UpdateApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: PATCH
