name: Build and ship App
on:
  workflow_dispatch: 
  # repository_dispatch:
  #   types: [terraform-completed] #trigger by the successful execution of terraform workflow
  push: 
    branches:
      - main


jobs:
  Build_react_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # verifying aws credentions
      - name: Setup and verify Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Testing Aws cli
        run: aws sts get-caller-identity

      - name: Install dependencies and build
        working-directory: Tinu-taskmanager
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          npm ci --legacy-peer-deps
          npm run build -- --outDir Taskmanager-build

############Saving build Artifiact 
      - name: Saving build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Taskmanager-build
          path: Tinu-taskmanager/Taskmanager-build

##Download artifact 
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Taskmanager-build
          path: Tinu-taskmanager/Taskmanager-build

      - name: Consume "$BUCKET_NAME" env from infra repo
        run: echo "BUCKET_NAME=${{ vars.BUCKET_NAME }}" >> $GITHUB_ENV
### Upload Build to s3
      - name: Upload build to s3
        working-directory: Tinu-taskmanager
        run: aws s3 sync Taskmanager-build s3://$BUCKET_NAME --delete

### Notification
      - name: Send success email via Mailgun
        if: success()
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
          -F from="${{ secrets.MAILGUN_FROM_EMAIL }}" \
          -F to=${{ secrets.MAILGUN_TO_EMAIL }} \
          -F subject="✅ TinuTaskmanager Build & Deploy Succeeded" \
          -F text="The GitHub Actions workflow completed successfully. The app has been deployed to S3."

      - name: Send failure email via Mailgun
        if: failure()
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
          -F from="${{ secrets.MAILGUN_FROM_EMAIL }}" \
          -F to=${{ secrets.MAILGUN_TO_EMAIL }} \
          -F subject="❌ TinuTaskmanager Build or Deploy Failed" \
          -F text="The GitHub Actions workflow failed. Please check the logs for more details."

        
