name: Terraform_s3_bucket
on:
  push:
    branches:
      - terraform_branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Enable debug logging
    env:
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform.log

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.1"
          terraform_wrapper: false
      
      - name: Setup and verify Aws Credentials
        run: |
          aws sts get-caller-identity

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd Tinu-taskmanager/terraform-s3-config
          terraform init -input=false
          terraform version
          terraform providers

      - name: Terraform Validate
        run: | 
          cd Tinu-taskmanager/terraform-s3-config
          terraform validate

      - name: Terraform plan
        run: |
          cd Tinu-taskmanager/terraform-s3-config
          terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Upload Terraform plan as artifact
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: taskmanager-plan
          path: tfplan







