name: Terraform_s3_bucket
on:
  push:
    branches:
      - terraform_branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Enable debug logging
    env:
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform.log

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.1"
          terraform_wrapper: false
      
      - name: Setup and verify Aws Credentials
        run: |
          aws sts get-caller-identity
          cd Tinu-taskmanager/terraform-s3-config
          pwd

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}






