name: Terraform_s3_bucket
on:
  push:
    branches:
      - terraform_branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Enable debug logging
    env:
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform.log
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.1"
          terraform_wrapper: false

      # verifying aws credentions 
      - name: Setup and verify Aws Credentials
        run: |
          aws sts get-caller-identity

      # Initiliazing terraform
      - name: Terraform Init
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: |
          terraform init -input=false
          terraform version
          terraform providers
      #validating terraform config
      - name: Terraform Validate
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: terraform validate
          
      #terraform Plan
      - name: Terraform plan
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: terraform plan -out=tfplan
      
      - name: DEBUG - check if tfplan exist 
        run: ls -la Tinu-taskmanager/terraform-s3-config

   

      # Upload Terraform plan as artifact...
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Tinu-taskmanager/terraform-s3-config/tfplan
          
      #Terraform Apply
      - name: Terraform Apply
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: | 
          terraform apply --auto-approve

      #save output file
      - name: Save Terraform output
        working-directory: Tinu-taskmanager/terraform-s3-config
        run:  |
          terraform output > output.txt
          ls-l

      - name: Upload output artifact...
        uses: actions/upload-artifact@v4
        with:
          name: output.txt
          path: Tinu-taskmanager/terraform-s3-config/output.txt
          
      - name: DEBUG - check for output.txt
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: ls-l



      # Terraform Destroy
      - name: Terraform Destroy
        working-directory: Tinu-taskmanager/terraform-s3-config
        run: |
          sleep 2m
          terraform destroy --auto-approve
        
        









